# Generated by Django 2.1 on 2018-08-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='menu_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя в Меню'),
        ),
        migrations.AddField(
            model_name='articles',
            name='menu_visible',
            field=models.BooleanField(default=0, verbose_name='Виден в Меню'),
        ),
    ]
